Mac M1 Documentation
DOI-USGS/asc-public-docs pull request #27
Opened 2023-12-27 19:13 UTC by amystamile-usgs

closes #15 

## Licensing
This project is mostly composed of free and unencumbered software released into the public domain, and we are unlikely to accept contributions that are not also released into the public domain. Somewhere near the top of each file should have these words:

> This work is free and unencumbered software released into the public domain. In jurisdictions that recognize copyright laws, the author or authors of this software dedicate any and all copyright interest in the software to the public domain.

- [x] I dedicate any and all copyright interest in this software to the public domain. I make this dedication for the benefit of the public at large and to the detriment of my heirs and successors. I intend this dedication to be an overt act of relinquishment in perpetuity of all present and future rights to this software under copyright law.

2023-12-27 19:33 UTC, Kelvinrr requested changes
~~some grammar errors picked up by the CI:~~ fixed before I finished the review lol 

The other changes still should be addressed

```
site/how-to-guides/isis-developer-guides/developing-mac-m1-arm-systems/index.html:2165: enviroment ==> environment
site/how-to-guides/isis-developer-guides/developing-mac-m1-arm-systems/index.html:2166: enviroment ==> environment
site/how-to-guides/isis-developer-guides/developing-mac-m1-arm-systems/index.html:2177: channnels ==> channels
```

2023-12-27 19:33 UTC, Kelvinrr commented on docs/how-to-guides/isis-developer-guides/developing-mac-m1-arm-systems.md
> +*By [Kris Becker](https://github.com/KrisBecker) (see original GitHub post [here](https://github.com/DOI-USGS/ISIS3/issues/5188))*
Maybe something more like "Borrowed largely from Kris Becker's original GH post". This page could diverge from the original post and we probably shouldn't imply Kris wrote every word on this page if it does.

2023-12-27 19:33 UTC, Kelvinrr commented on docs/how-to-guides/isis-developer-guides/developing-mac-m1-arm-systems.md
> +
Maybe we could leave this detail out? It can be documented via the GH post above.

2023-12-27 19:33 UTC, Kelvinrr commented on docs/how-to-guides/isis-developer-guides/developing-mac-m1-arm-systems.md
> +Note that my M1 Mac system currently runs Apple macOS Monterey. Here is some additional information regarding the system used to install, configure and build ISIS on the M1:
We should not make it first person, update this with an [admonition](https://squidfunk.github.io/mkdocs-material/reference/annotations/#in-content-tabs-tab-1) like: 

```markdown
???+ note

    This guide is based on a M1 Mac system running Apple macOS Monterey. Here is some additional information regarding the system used to install, configure and build ISIS on the M1:

    ```
    Hardware Overview
      Model Name:	MacBook Pro
      Model Identifier:	MacBookPro18,2
      Chip:	Apple M1 Max
      Total Number of Cores:	10 (8 performance and 2 efficiency)
      Memory:	32 GB
    Graphics/Display
      Type:	GPU
      Bus:	Built-In
      Total Number of Cores:	24
    System Software Overview:
      System Version:	macOS 12.6.3 (21G419)
      Kernel Version:	Darwin 21.6.0
    ```
```

2023-12-27 19:33 UTC, Kelvinrr commented on docs/how-to-guides/isis-developer-guides/developing-mac-m1-arm-systems.md
> +```
This can probably also be part of an admonition.

2023-12-27 19:33 UTC, Kelvinrr commented on docs/how-to-guides/isis-developer-guides/developing-mac-m1-arm-systems.md
> +Before ISIS can be built, the conda environment must be installed on the Mac M1. I use [Miniconda](https://docs.conda.io/projects/miniconda/en/latest/) to maintain the least possible environment that
More first person language we can probably change.

2023-12-27 19:33 UTC, Kelvinrr commented on docs/how-to-guides/isis-developer-guides/developing-mac-m1-arm-systems.md
> +
More first-person language at the end here.

2023-12-27 19:33 UTC, Kelvinrr commented on docs/how-to-guides/isis-developer-guides/developing-mac-m1-arm-systems.md
> +I will just mention that Amazon provides [EC2 Mac instances](https://aws.amazon.com/ec2/instance-types/mac/), which includes M1 systems with Monterey installed that may help those who have access to
First person language here again.

2023-12-27 22:41 UTC, amystamile-usgs commented
@Kelvinrr I think I removed all of the first person use. Let me know if I missed any.

2023-12-28 15:30 UTC, Kelvinrr approved these changes
downloaded the artifacts and it looks good to me.

2023-12-28 15:36 UTC, merged